name: Duzzle Dev API Server Deployment
on:
  push:
    branches: [ dev ]

  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Add Droplet to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Copy files via scp
        run: |
          scp -r ./dist ${{ secrets.DO_SSH_USER }}@${{ secrets.DROPLET_IP }}:/home/${{ secrets.DO_SSH_USER }}/duzzle-be

      - name: Install PM2 if not installed and restart application
        run: |
          ssh ${{ secrets.DO_SSH_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
          if ! command -v pm2 > /dev/null; then
            npm install -g pm2
          fi
          cd /home/${{ secrets.DO_SSH_USER }}/duzzle-be/dist
          npm install --production
          pm2 restart all || pm2 start dist/src/main.js --name duzzle-be
          EOF
      - name: Install dependencies on server
        run: |
          ssh ${{ secrets.DO_SSH_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
          cd /home/${{ secrets.DO_SSH_USER }}/duzzle-be/dist
          npm install --production
          pm2 restart all || pm2 start dist/src/main.js --name duzzle-be
          EOF
        env:
          SSH_USER: ${{ secrets.DO_SSH_USER }}
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
